In [9]:
"""
Consider the below code to answer further questions:
"""
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

list_      :  ['1', '2', '3', '4', '5'] , Type :  <class 'list'>
array_list :  ['1' '2' '3' '4' '5'] , Type :  <class 'numpy.ndarray'>


In [11]:
"""
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.
"""
# list_ is a list, ordered (indexed) collection of heterogeneos elements whereas array_list is an array, ordered (indexed) collection of homogeneos elements 
print('list_      : ', list_, ', type(list_) : ', type(list_))
print('array_list : ', array_list, ', type(array_list) : ', type(array_list))

list_      :  ['1', '2', '3', '4', '5'] , type(list_) :  <class 'list'>
array_list :  ['1' '2' '3' '4' '5'] , type(array_list) :  <class 'numpy.ndarray'>


In [13]:
"""
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.
"""
print('list_ \n')
for e in list_:
    print(e, type(e))
    
print('\narray_list \n')
for e in array_list:
    print(e, type(e))

list_ 

1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>

array_list 

1 <class 'numpy.str_'>
2 <class 'numpy.str_'>
3 <class 'numpy.str_'>
4 <class 'numpy.str_'>
5 <class 'numpy.str_'>


In [15]:
"""
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
"""
array_list = np.array(object = list_, dtype = int) # datatype of list_ elements would not change, datatype of array_list elements would be numpy.int64 instead of numpy.str

print('list_ \n')
for e in list_:
    print(e, type(e))
    
print('\narray_list \n')
for e in array_list:
    print(e, type(e))

list_ 

1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>

array_list 

1 <class 'numpy.int64'>
2 <class 'numpy.int64'>
3 <class 'numpy.int64'>
4 <class 'numpy.int64'>
5 <class 'numpy.int64'>


In [17]:
"""
Consider the below code to answer further questions:
"""
import numpy as np
num_list  = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

print('num_list \n', num_list )
print('num_array \n', num_array)

num_list 
 [[1, 2, 3], [4, 5, 6]]
num_array 
 [[1 2 3]
 [4 5 6]]


In [20]:
"""
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size
"""
print(f'shape - {num_array.shape}') # shape (rows, columns)
print(f'size  - {num_array.size}') # total number of elements

shape - (2, 3)
size  - 6


In [22]:
"""
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]
"""
a = np.zeros(9).reshape(3, 3)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
"""
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
"""
a = np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
